# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5108567f2d0b01be8a3d480a871e2e072a4e8415395bdee9624b808b05f2add1792a81670b5db706e0ad616aa82b1e305ec43bc9c458eaa63c9b3a1ff447d3f6

test:
  secret_key_base: 45fcb8fd3c17cd6f44b53d78c92d3a7ea9e4edc9bec1314036121ae0d6e9271c925a1567dd992b42f763020d7a65d5cae789ca6ba203e078ae0839ea4c8f1bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
